# Generated by Django 2.1 on 2018-09-07 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_auto_20180906_2355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('list_desc', models.TextField()),
                ('list_image', models.ImageField(blank=True, null=True, upload_to='list_images')),
            ],
        ),
        migrations.CreateModel(
            name='UserListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_userlist', to='books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlist_author', to='account.UserList')),
            ],
        ),
        migrations.AddField(
            model_name='userlist',
            name='book',
            field=models.ManyToManyField(related_name='user_list_books', through='account.UserListEntry', to='books.Book'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
