# Generated by Django 2.1 on 2018-09-09 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180907_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlist',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='user_list_books', through='account.UserListEntry', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='userlistentry',
            name='user_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlist_contents', to='account.UserList'),
        ),
    ]
