# Generated by Django 2.1 on 2018-09-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180909_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='slug',
        ),
    ]
