# Generated by Django 2.1 on 2018-09-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_auto_20180906_2355'),
        ('account', '0004_remove_userlist_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlistentry',
            unique_together={('user_list', 'book')},
        ),
    ]
