# Generated by Django 2.1 on 2018-09-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userlist_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='public',
            field=models.BooleanField(),
        ),
    ]
