# Generated by Django 2.1 on 2018-09-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180912_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='public',
        ),
        migrations.AddField(
            model_name='userlist',
            name='not_public',
            field=models.BooleanField(default=False, help_text="Don't make this list available to other users."),
        ),
    ]
