# Generated by Django 2.0.1 on 2018-08-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=10101, max_length=30),
            preserve_default=False,
        ),
    ]
