# Generated by Django 2.0.1 on 2018-08-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_author_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('region_name',),
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('school_name',),
            },
        ),
        migrations.AddField(
            model_name='author',
            name='featured_author',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='regions',
            field=models.ManyToManyField(blank=True, to='authors.Region'),
        ),
        migrations.AddField(
            model_name='author',
            name='schools',
            field=models.ManyToManyField(blank=True, to='authors.School'),
        ),
    ]
