# Generated by Django 2.0.1 on 2018-08-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_author_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
