# Generated by Django 2.0.1 on 2018-08-28 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0007_auto_20180824_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='author_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
