# Generated by Django 2.1 on 2018-09-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_author_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('awards', 'awards'), ('editorial', 'editorial')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('list_desc', models.TextField()),
                ('list_image', models.ImageField(blank=True, null=True, upload_to='list_images')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_list', to='authors.Author')),
                ('author_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_list', to='authors.AuthorList')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='lists',
            field=models.ManyToManyField(related_name='author_lists', through='authors.AuthorListEntry', to='authors.AuthorList'),
        ),
    ]
