# Generated by Django 2.1 on 2018-10-01 19:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_auto_20180911_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=tinymce.models.HTMLField(verbose_name='Bio'),
        ),
    ]
