# Generated by Django 2.1 on 2018-10-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_auto_20181001_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image_credit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
