# Generated by Django 2.0.1 on 2018-08-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1011, max_length=30),
            preserve_default=False,
        ),
    ]
