# Generated by Django 2.0.1 on 2018-08-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
