# Generated by Django 2.0.1 on 2018-08-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_year',
            field=models.IntegerField(default=1999),
            preserve_default=False,
        ),
    ]
