# Generated by Django 2.0.1 on 2018-08-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_pub_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
