# Generated by Django 2.0.1 on 2018-08-23 17:14

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_book_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_country',
            field=django_countries.fields.CountryField(default=12, max_length=2),
            preserve_default=False,
        ),
    ]
