# Generated by Django 2.0.1 on 2018-08-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_book_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('theme_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('book_title',)},
        ),
        migrations.AddField(
            model_name='book',
            name='themes',
            field=models.ManyToManyField(blank=True, to='books.Theme'),
        ),
    ]
