# Generated by Django 2.0.1 on 2018-08-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20180823_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('setting_name',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='settings',
            field=models.ManyToManyField(blank=True, to='books.Setting'),
        ),
    ]
