# Generated by Django 2.1 on 2018-08-26 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_booklike'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_liked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_liked', to='books.BookLike'),
            preserve_default=False,
        ),
    ]
