# Generated by Django 2.1 on 2018-09-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_auto_20180906_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='kind',
            field=models.CharField(choices=[('AWARDS', 'Awards'), ('EDITORIAL', 'Editorial')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
