# Generated by Django 2.1 on 2018-09-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_booklist_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booklist',
            name='kind',
            field=models.CharField(choices=[('awards', 'awards'), ('editorial', 'editorial')], max_length=20),
        ),
    ]
