# Generated by Django 2.1 on 2018-09-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20180906_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='list_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booklist',
            name='list_image',
            field=models.ImageField(blank=True, null=True, upload_to='list_images'),
        ),
    ]
