# Generated by Django 2.1 on 2018-10-01 19:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_auto_20180906_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_desc',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
