# Generated by Django 2.1 on 2018-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_auto_20181001_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_credit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
